const INCREASE = "INCREASE";
const DECREASE = "DECREASE";
const REMOVE = "REMOVE";
const CLEAR_CART = "CLEAR_CART";
const LOADING = "LOADING";
const DISPLAY_ITEMS = "DISPLAY_ITEMS";

export { INCREASE, DECREASE, REMOVE, CLEAR_CART, LOADING, DISPLAY_ITEMS };
