const INCREASE = "INCREASE";
const DECREASE = "DECREASE";
const REMOVE = "REMOVE";
const CLEAR_ITEMS = "CLEAR_ITEMS";
const LOADING = "LOADING";
const DISPLAY_ITEMS = "DISPLAY_ITEMS";

export { INCREASE, DECREASE, REMOVE, CLEAR_ITEMS, LOADING, DISPLAY_ITEMS };
